version: "3.8"

services:
  db:
    image: mysql:8
    ports:
      - "3307"
    environment:
      MYSQL_ROOT_PASSWORD: nextjs
      MYSQL_DATABASE: nextjs

  nextjs:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    container_name: next_ssr
    restart: always
    depends_on:
      - db
