import "./globals.css";
import { NavBar } from "./components/nav-bar";
import { Toaster } from "@/components/ui/toaster";
import { Geist } from "next/font/google";

const geistSans = Geist({
  subsets: ["latin"],
  display: "optional",
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={geistSans.className}>
      <body className={`antialiased`}>
        <NavBar />
        {children}
        <Toaster />
      </body>
    </html>
  );
}
